pipeline {
    agent {
	label "machine"}
    stages {
        stage('Build') {
            steps {
                powershell label: 'Building Project', script: '.\\gradlew.bat build'
            }
        }
           
    }
}
